export const actionTypes = {

    REQUEST_USERS: 'REQUEST_USERS',
    REQUEST_USERS_SUCCESS: 'REQUEST_USERS_SUCCESS',
    REQUEST_USERS_FAILED: 'REQUEST_USERS_FAILED',
    ADD_NEW_USER: 'ADD_NEW_USER',
    UPDATE_USER: 'UPDATE_USER',




}